[package]

name = "termbox"
version = "0.0.0-alpha"
authors = []
license = "MIT"
description = "A Rust wrapper for the termbox library"

[lib]

name = "termbox"
path = "src/lib.rs"

[dependencies.termbox_sys]

path = "termbox_sys"
