[package]

name = "termbox"
version = "0.0.0-alpha"
authors = []
license = "MIT"
description = "A Rust wrapper for the termbox library"

links = "termbox"
build = "build.rs"

[lib]

name = "termbox"
path = "src/lib.rs"
